# Generated by Django 3.1.1 on 2020-09-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
