# Generated by Django 3.1.1 on 2020-09-21 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_auto_20200921_1655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.departments', verbose_name='Отдел')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.workers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
