# Generated by Django 3.1.1 on 2020-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='file',
            field=models.FileField(default=123, upload_to='static/incidents/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
