# Generated by Django 3.1.4 on 2021-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
        ),
    ]
