# Generated by Django 3.1.4 on 2021-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210211_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
