# Generated by Django 3.1.1 on 2020-10-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_measure'),
        ('tender', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.measure'),
        ),
    ]
