# Generated by Django 3.1.1 on 2020-10-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='tender.participant'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='tender.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Товар'),
        ),
    ]
