# Generated by Django 3.1.1 on 2020-10-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_auto_20201013_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.AlterField(
            model_name='goods',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.product', verbose_name='Товар'),
        ),
    ]
