# Generated by Django 3.1.1 on 2020-10-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_auto_20201019_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.participant')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.provider')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.tender')),
            ],
        ),
    ]
