# Generated by Django 3.1.1 on 2020-10-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0015_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='provider',
        ),
        migrations.AddField(
            model_name='price',
            name='goods',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='tender.goods'),
            preserve_default=False,
        ),
    ]
