# Generated by Django 3.1.1 on 2020-10-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0016_auto_20201019_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.price')),
            ],
        ),
    ]
