# Generated by Django 3.1.1 on 2020-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0019_auto_20201107_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
