# Generated by Django 3.1.1 on 2020-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0020_tender_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
