# Generated by Django 3.1.1 on 2020-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0021_tender_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
