# Generated by Django 3.1.1 on 2020-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0022_auto_20201127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
