# Generated by Django 3.1.1 on 2020-12-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tender', '0024_auto_20201203_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='cfo_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='cfo_confirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='cfo_confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='cpo_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='cpo_confirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.tender')),
            ],
        ),
    ]
